name: Build Swift Android Emulator Demo
on:       
  push:
    branches: '*'
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        api-level: [29]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: skiptools/swift-android-action@main
        id: setup-toolchain
        with:
          swift-version: nightly-6.2
          # just set up the toolchain but don't build anything
          build-package: false

      - run: |
          mkdir ExecutableDemo
          cd ExecutableDemo
          swift package init --type executable
          ${{ steps.setup-toolchain.outputs.swift-build }} -c debug

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run commands
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb push ExecutableDemo/.build/debug/ExecutableDemo /data/local/tmp/
            adb shell /data/local/tmp/ExecutableDemo

      - name: run commands again
        run: |
          adb push ExecutableDemo/.build/debug/ExecutableDemo /data/local/tmp/
          adb shell /data/local/tmp/ExecutableDemo
